name: Games

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create bin folder
        run: mkdir -p mp/game/mod_hl2mp/bin
      - name: Run VPC
        run: mp/src/creategameprojects
      # VPC writes absolute paths which can become annoying so we have to "sanitize" them to be relative.
      - name: Sanitize paths
        run: |
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/games.mak
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/game/client/client_linux32_hl2mp.mak
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/game/server/server_linux32_hl2mp.mak
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/mathlib/mathlib_linux32.mak
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/raytrace/raytrace_linux32.mak
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/tier1/tier1_linux32.mak
          sed -e "s|${{ github.workspace }}/||g" -i mp/src/vgui2/vgui_controls/vgui_controls_linux32.mak
      - name: Build
        uses: docker://registry.gitlab.steamos.cloud/steamrt/scout/sdk/i386:latest
        with:
          args: make GITHUB_ACTIONS=1 -f mp/src/games.mak
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86
          path: |
            mp/game/mod_hl2mp/bin/client.so
            mp/game/mod_hl2mp/bin/client.so.dbg
            mp/game/mod_hl2mp/bin/server.so
            mp/game/mod_hl2mp/bin/server.so.dbg
